# Generated by Django 3.1.1 on 2020-10-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name_plural': 'Oldal adatok'},
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='footer',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_name',
            field=models.CharField(max_length=200, verbose_name='Oldalnév'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Alcím'),
        ),
    ]
