# Generated by Django 3.1.1 on 2020-10-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201010_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logo', verbose_name='Logo'),
        ),
    ]
