# Generated by Django 3.1.1 on 2020-10-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201011_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('photo', models.ImageField(upload_to='services', verbose_name='Kép')),
                ('content', models.TextField(max_length=5000, verbose_name='Leírás')),
            ],
            options={
                'verbose_name_plural': 'Szolgáltatásaink',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'Magunkról'},
        ),
    ]
