# Generated by Django 3.1.1 on 2020-10-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201011_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Címsor')),
                ('content', models.TextField(max_length=5000, verbose_name='Bemutatkozó')),
            ],
            options={
                'verbose_name_plural': 'Nyitó oldal',
            },
        ),
    ]
